### PR TITLE
added daju picture thamk u vai mcuh

### PR DESCRIPTION
**Pull request by rajdeep-biswas**

### CODE REVIEW

**Comment by Aashutoshbro** [comment]
Np

**Comment by Aashutoshbro** [comment]
@rajdeep-biswas Bro you can invite other too i will teach them if they don't know or simply i will accept if criteria gets up

**Comment by rajdeep-biswas** [comment]
U sir merge first then I gib more kanchaz,.

**Comment by Aashutoshbro** [comment]
Thank u

**Pull request closed without merging**
